namespace LittleMoon.AnsiConsole
{
    public enum AnsiCode
    {
        Default____ = 0,
        Bold____ = 1,
        Underline____ = 2,
        No_underline____ = 3,
        Negative____ = 4,
        Positive____ = 5,
        Foreground_Black____ = 6,
        Foreground_Red____ = 7,
        Foreground_Green____ = 8,
        Foreground_Yellow____ = 9,
        Foreground_Blue____ = 10,
        Foreground_Magenta____ = 11,
        Foreground_Cyan____ = 12,
        Foreground_White____ = 13,
        Foreground_Default____ = 14,
        Background_Black____ = 15,
        Background_Red____ = 16,
        Background_Green____ = 17,
        Background_Yellow____ = 18,
        Background_Blue____ = 19,
        Background_Magenta____ = 20,
        Background_Cyan____ = 21,
        Background_White____ = 22,
        Background_Extended____ = 23,
        Background_Default____ = 24,
        Bright_Foreground_Black____ = 25,
        Bright_Foreground_Red____ = 26,
        Bright_Foreground_Green____ = 27,
        Bright_Foreground_Yellow____ = 28,
        Bright_Foreground_Blue____ = 29,
        Bright_Foreground_Magenta____ = 30,
        Bright_Foreground_Cyan____ = 31,
        Bright_Foreground_White____ = 32,
        Bright_Background_Black____ = 33,
        Bright_Background_Red____ = 34,
        Bright_Background_Green____ = 35,
        Bright_Background_Yellow____ = 36,
        Bright_Background_Blue____ = 37,
        Bright_Background_Magenta____ = 38,
        Bright_Background_Cyan____ = 39,
        Bright_Background_White____ = 40,
        Draw_SE____ = 41,
        Draw_NE____ = 42,
        Draw_NW____ = 43,
        Draw_SW____ = 44,
        Draw_Cross____ = 45,
        Draw_Horizontal____ = 46,
        Draw_MiddleLeft____ = 47,
        Draw_MiddleRight____ = 48,
        Draw_BottomT____ = 49,
        Draw_TopT____ = 50,
        Draw_Vertical____ = 51,
    }
}